language: java
install: true
services:
- docker
before_script:
- "docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASS -e $ARTIFACTORY_EMAIL"
script:
- "./gradlew bootRepackage publishToMavenLocal artifactoryPublish dockerPushImage"
