management:
  port: 9080
hachiman:
  ingest:
    group: ${INGEST_GROUP:ingest}
    kafka:
      topic: ${INGEST_KAFKA_TOPIC:ingest}
      zookeepers: ${INGEST_KAFKA_ZOOKEEPERS:localhost:2181}
      brokers: ${INGEST_KAFKA_BROKERS:localhost:9092}
    riak:
      bucket: ${INGEST_RIAK_BUCKET:ingest}
      surrogateKey: ${INGEST_RIAK_SURROGATE_KEY:surrogate_key}
      surrogateKeyValue: ${INGEST_RIAK_SURROGATE_KEY_VALUE:k}
      surrogateFamily: ${INGEST_RIAK_SURROGATE_FAMILY:surrogate_family}
      surrogateFamilyValue: ${INGEST_RIAK_SURROGATE_FAMILY_VALUE:f}
      offsetKey: ${INGEST_RIAK_OFFSET_KEY:offset}
      kv-bucket: ${INGEST_RIAK_KV_BUCKET:ingest-kv}
      kv-key: ${INGEST_RIAK_KV_KEY:timestamp}
      hosts: ${INGEST_RIAK_HOSTS:localhost:8087}
      schema: ${INGEST_RIAK_SCHEMA:varchar,varchar,timestamp,double,double,double}