hachiman:
  ingest:
    group: ${INGEST_GROUP:default}
    riak:
      hosts: ${INGEST_RIAK_HOSTS:localhost:8087}
    config:
      riak:
        timeout: 5
        pollInterval: 60
        bucket: ${INGEST_CONFIG_BUCKET:config}
