hachiman:
  ingest:
    group: ${INGEST_GROUP:default}
    riak:
      hosts: ${INGEST_RIAK_HOSTS:localhost:8087}
    kafka:
      zookeepers: ${INGEST_ZK_HOSTS:localhost:2181}
    config:
      riak:
        timeout: ${INGEST_RIAK_TIMEOUT_SECS:5}
        pollInterval: ${INGEST_RIAK_POLL_INTERVAL_SECS:60}
